# Generated by Django 5.2.3 on 2025-11-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField(help_text='Heart rate in BPM')),
                ('blood_oxygen', models.FloatField(help_text='Blood oxygen percentage (SpO2)')),
                ('hrv', models.FloatField(blank=True, help_text='Heart rate variability in ms', null=True)),
                ('respiratory_rate', models.FloatField(blank=True, help_text='Breaths per minute', null=True)),
                ('total_sleep_hours', models.FloatField(blank=True, null=True)),
                ('deep_sleep_hours', models.FloatField(blank=True, null=True)),
                ('rem_sleep_hours', models.FloatField(blank=True, null=True)),
                ('core_sleep_hours', models.FloatField(blank=True, null=True)),
                ('awake_time_hours', models.FloatField(blank=True, null=True)),
                ('awakenings_count', models.IntegerField(default=0, help_text='Number of times woke up during night')),
                ('sleep_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10, null=True)),
                ('fall_detected', models.BooleanField(default=False)),
                ('fall_resolved', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(help_text='When the data was recorded on Watch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watch_vitals',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='watch_vital_user_id_3350c1_idx')],
            },
        ),
    ]
