# Generated by Django 5.2.3 on 2025-11-29 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0003_watchvitals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchvitals',
            constraint=models.UniqueConstraint(fields=('user', 'recorded_at'), name='unique_vitals_per_timestamp'),
        ),
    ]
