# Generated by Django 5.2.3 on 2025-06-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDayTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taken', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, help_text='Notes about the day', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_tracking', to='courses.course')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_tracking', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-date', 'time'],
                'unique_together': {('course', 'medicine', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='CourseMedicineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('dosage', models.CharField(help_text='e.g., 1 tablet, 2 capsules', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_schedules', to='courses.course')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='medicines.medicine')),
            ],
            options={
                'ordering': ['time'],
                'unique_together': {('course', 'medicine', 'time')},
            },
        ),
    ]
