# Generated by Django 5.2.3 on 2025-06-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], default='non_vegetarian', max_length=20)),
                ('dietary_restrictions', models.TextField(blank=True, help_text='e.g., allergies, religious, medical', null=True)),
                ('daily_water_intake', models.DecimalField(decimal_places=1, default=2.0, help_text='Liters per day', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.BooleanField(default=False)),
                ('drink_alcohol', models.BooleanField(default=False)),
                ('caffeine_intake', models.PositiveIntegerField(default=0, help_text='Cups of tea/coffee/energy drinks per day')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_medications', models.BooleanField(default=False)),
                ('current_medications', models.TextField(blank=True, help_text='List of current medications', null=True)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, help_text='Specify allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g., diabetes, hypertension', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experienced_anxiety_depression', models.BooleanField(default=False)),
                ('seeing_therapist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_frequency', models.CharField(choices=[('never', 'Never'), ('1-2', '1-2 times per week'), ('3-4', '3-4 times per week'), ('5-6', '5-6 times per week'), ('daily', 'Daily')], default='never', max_length=10)),
                ('exercise_type', models.CharField(blank=True, help_text='e.g., walking, running, gym, yoga', max_length=100, null=True)),
                ('average_duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
            ],
        ),
    ]
