# Generated by Django 5.2.3 on 2025-06-22 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietaryhabits',
            name='health_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_habits', to='health_profile.healthprofile'),
        ),
        migrations.AddField(
            model_name='lifestylehabits',
            name='health_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_habits', to='health_profile.healthprofile'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='health_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='health_profile.healthprofile'),
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='health_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mental_health', to='health_profile.healthprofile'),
        ),
        migrations.AddField(
            model_name='physicalactivity',
            name='health_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_activity', to='health_profile.healthprofile'),
        ),
    ]
