# Generated by Django 5.2.3 on 2025-12-25 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0004_add_unique_vitals_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchvitals',
            name='awake_time_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='awakenings_count',
            field=models.IntegerField(default=0, help_text='Number of times woke up during night', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='blood_oxygen',
            field=models.FloatField(help_text='Blood oxygen percentage SpO2 (valid range: 50-100)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='core_sleep_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='deep_sleep_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='heart_rate',
            field=models.FloatField(help_text='Heart rate in BPM (valid range: 30-250)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='hrv',
            field=models.FloatField(blank=True, help_text='Heart rate variability in ms (valid range: 1-300)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='rem_sleep_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='respiratory_rate',
            field=models.FloatField(blank=True, help_text='Breaths per minute (valid range: 5-60)', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='watchvitals',
            name='total_sleep_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
