# Generated by Django 5.2.3 on 2025-12-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0005_alter_watchvitals_awake_time_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchvitals',
            name='calories',
            field=models.IntegerField(default=0, help_text='Active calories burned'),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='distance_km',
            field=models.FloatField(default=0, help_text='Distance in kilometers'),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='exercise_minutes',
            field=models.IntegerField(default=0, help_text='Exercise minutes'),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='floors_climbed',
            field=models.IntegerField(default=0, help_text='Floors climbed'),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='stand_minutes',
            field=models.IntegerField(default=0, help_text='Stand minutes'),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='steps',
            field=models.IntegerField(default=0, help_text='Daily step count'),
        ),
    ]
