# Generated by Django 5.2.3 on 2026-01-09 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0006_add_activity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchvitals',
            name='afib_burden_percent',
            field=models.FloatField(blank=True, help_text='AFib burden percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='afib_detected',
            field=models.BooleanField(default=False, help_text='AFib detected in ECG'),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='blood_glucose',
            field=models.FloatField(blank=True, help_text='Blood glucose in mg/dL', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='blood_pressure_diastolic',
            field=models.FloatField(blank=True, help_text='Diastolic blood pressure in mmHg', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='blood_pressure_systolic',
            field=models.FloatField(blank=True, help_text='Systolic blood pressure in mmHg', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='body_temperature',
            field=models.FloatField(blank=True, help_text='Body temperature in Celsius', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='double_support_time_percent',
            field=models.FloatField(blank=True, help_text='Double support time percentage - balance indicator', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='peripheral_perfusion_index',
            field=models.FloatField(blank=True, help_text='Peripheral perfusion index percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='six_minute_walk_distance',
            field=models.FloatField(blank=True, help_text='Six-minute walk test distance in meters', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='stair_ascent_speed',
            field=models.FloatField(blank=True, help_text='Stair ascent speed in m/s', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='stair_descent_speed',
            field=models.FloatField(blank=True, help_text='Stair descent speed in m/s', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='vo2_max',
            field=models.FloatField(blank=True, help_text='VO2 Max in mL/kg/min', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='walking_asymmetry_percent',
            field=models.FloatField(blank=True, help_text='Walking asymmetry percentage - gait imbalance indicator', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='walking_speed',
            field=models.FloatField(blank=True, help_text='Walking speed in m/s', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='walking_steadiness_classification',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Low', 'Low'), ('Very Low', 'Very Low')], help_text='Classification: OK (>=75%), Low (50-75%), Very Low (<50%)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='walking_steadiness_percent',
            field=models.FloatField(blank=True, help_text='Walking steadiness percentage (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='watchvitals',
            name='wrist_temperature_delta',
            field=models.FloatField(blank=True, help_text='Wrist temperature delta from baseline (iOS 16+)', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
