# Generated by Django 5.2.3 on 2025-11-29 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0003_alter_biomarker_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='conflict_note',
            field=models.TextField(blank=True, help_text='Details about conflicting values', null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='extraction_confidence',
            field=models.FloatField(default=1.0, help_text='Confidence score from AI extraction (0-1)'),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='facility_name',
            field=models.CharField(blank=True, help_text='Hospital/lab facility name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='has_conflict',
            field=models.BooleanField(default=False, help_text='True if conflicting values exist for same test/date'),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='is_manually_entered',
            field=models.BooleanField(default=False, help_text='True if entered manually by user'),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Primary reading when multiple exist for same date'),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='True if value has been validated against expected ranges'),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='laboratory_name',
            field=models.CharField(blank=True, help_text='Lab where test was performed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, help_text='Standardized biomarker name for matching', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='normalized_unit',
            field=models.CharField(blank=True, help_text='Standard unit (SI or US based on user preference)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='normalized_value',
            field=models.FloatField(blank=True, help_text='Value converted to standard unit for comparison', null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='provider_name',
            field=models.CharField(blank=True, help_text='Doctor/provider name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='test_time',
            field=models.TimeField(blank=True, help_text='Time when test was performed (if available)', null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='validation_warning',
            field=models.TextField(blank=True, help_text='Warning message if value seems unusual', null=True),
        ),
        migrations.AddIndex(
            model_name='biomarker',
            index=models.Index(fields=['user', 'normalized_name', '-test_date'], name='medical_rep_user_id_723436_idx'),
        ),
        migrations.AddIndex(
            model_name='biomarker',
            index=models.Index(fields=['user', 'facility_name'], name='medical_rep_user_id_523fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='biomarker',
            index=models.Index(fields=['user', '-test_date'], name='medical_rep_user_id_341458_idx'),
        ),
        migrations.AddConstraint(
            model_name='biomarker',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'test_date', 'facility_name'), name='unique_biomarker_per_facility_date'),
        ),
    ]
