# Generated by Django 5.2.3 on 2025-12-07 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0004_add_biomarker_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biomarker_name', models.CharField(db_index=True, help_text='Biomarker this insight relates to', max_length=255)),
                ('insight_type', models.CharField(choices=[('biomarker_analysis', 'Biomarker Analysis'), ('trend_analysis', 'Trend Analysis'), ('correlation', 'Correlation with Other Data'), ('medication_interaction', 'Medication Interaction'), ('lifestyle_recommendation', 'Lifestyle Recommendation'), ('research_finding', 'Research-Based Finding')], default='biomarker_analysis', max_length=30)),
                ('title', models.CharField(help_text='Short, descriptive title', max_length=500)),
                ('summary', models.TextField(help_text='Brief summary for display')),
                ('detailed_analysis', models.TextField(help_text='Full AI-generated analysis')),
                ('user_context', models.JSONField(default=dict, help_text='User data considered: medications, other biomarkers, history')),
                ('research_references', models.JSONField(default=list, help_text='List of research citations and sources')),
                ('research_summary', models.TextField(blank=True, help_text='Summary of relevant research findings', null=True)),
                ('biomarker_value', models.FloatField(blank=True, null=True)),
                ('biomarker_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_min', models.FloatField(blank=True, null=True)),
                ('reference_max', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, help_text='normal, high, low, critical_high, critical_low', max_length=20, null=True)),
                ('deviation_percent', models.FloatField(blank=True, help_text='How far from normal range in %', null=True)),
                ('trend_direction', models.CharField(blank=True, help_text='improving, worsening, stable', max_length=20, null=True)),
                ('trend_percentage', models.FloatField(blank=True, null=True)),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical - Requires Immediate Attention'), ('warning', 'Warning - Needs Monitoring'), ('info', 'Informational'), ('success', 'Normal/Healthy')], default='info', max_length=20)),
                ('urgency', models.CharField(choices=[('immediate', 'Immediate Action Required'), ('soon', 'Address Within Days'), ('routine', 'Discuss at Next Appointment'), ('none', 'No Action Needed')], default='routine', max_length=20)),
                ('recommendations', models.JSONField(default=list, help_text='List of actionable recommendations')),
                ('doctor_discussion_points', models.JSONField(default=list, help_text='Points to discuss with doctor')),
                ('lifestyle_tips', models.JSONField(default=list, help_text='Lifestyle modifications')),
                ('related_biomarkers', models.JSONField(default=list, help_text='Other biomarkers that correlate')),
                ('related_medications', models.JSONField(default=list, help_text='Medications that may affect this')),
                ('requires_doctor_visit', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('generation_prompt_version', models.CharField(default='v1', max_length=20)),
                ('biomarker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='medical_reports.biomarker')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='medical_reports.uploadedmedicalreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='medical_rep_user_id_0fb844_idx'), models.Index(fields=['user', 'biomarker_name', '-created_at'], name='medical_rep_user_id_ee35dd_idx'), models.Index(fields=['user', 'severity', '-created_at'], name='medical_rep_user_id_9e510c_idx'), models.Index(fields=['user', 'is_dismissed', '-created_at'], name='medical_rep_user_id_7951dc_idx'), models.Index(fields=['report', '-created_at'], name='medical_rep_report__d3d067_idx')],
            },
        ),
    ]
