# Generated by Django 5.2.3 on 2025-06-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_situation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='patient_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
