# Generated by Django 5.2.3 on 2025-07-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_processing_result_userjson_summarize_patient_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjson',
            name='summarize_patient_report',
            field=models.CharField(blank=True, null=True),
        ),
    ]
