# Generated by Django 5.2.3 on 2025-08-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_conservation_choice',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
