# Generated by Django 5.2.3 on 2025-10-03 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0001_initial'),
        ('medicines', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded_reports/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from document', null=True)),
                ('biomarkers', models.JSONField(blank=True, default=dict, help_text='Extracted biomarkers and lab values')),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes and recommendations", null=True)),
                ('diagnoses', models.JSONField(blank=True, default=list, help_text='List of diagnoses from report')),
                ('medication_recommendations', models.JSONField(blank=True, default=list, help_text='Extracted medication changes')),
                ('report_date', models.DateField(blank=True, help_text='Date of the medical report itself', null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('changes_applied', 'Changes Applied'), ('dismissed', 'Dismissed')], default='pending_review', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(db_index=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('change_type', models.CharField(choices=[('new', 'New Medication'), ('dosage_change', 'Dosage Change'), ('schedule_change', 'Schedule Change'), ('discontinue', 'Discontinue'), ('frequency_change', 'Frequency Change')], max_length=20)),
                ('old_value', models.JSONField(blank=True, help_text='Previous medication details', null=True)),
                ('new_value', models.JSONField(help_text='New medication details (dosage, frequency, schedule, etc.)')),
                ('reason', models.TextField(blank=True, help_text="Doctor's reason for the change", null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('failed', 'Failed to Apply')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissal_reason', models.TextField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('applied_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_recommendation', to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_recommendations', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='medical_reports.uploadedmedicalreport')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='e.g., HbA1c, Cholesterol, Glucose', max_length=255)),
                ('value', models.FloatField(help_text='Numeric value')),
                ('unit', models.CharField(help_text='e.g., mg/dL, mmol/L, %', max_length=50)),
                ('reference_min', models.FloatField(blank=True, null=True)),
                ('reference_max', models.FloatField(blank=True, null=True)),
                ('is_normal', models.BooleanField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, help_text='H (high), L (low), N (normal)', max_length=10, null=True)),
                ('test_date', models.DateField(help_text='Date when the test was performed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarkers', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_biomarkers', to='medical_reports.uploadedmedicalreport')),
            ],
            options={
                'ordering': ['user', 'name', '-test_date'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedmedicalreport',
            index=models.Index(fields=['user', 'status'], name='medical_rep_user_id_e3bd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedmedicalreport',
            index=models.Index(fields=['user', '-uploaded_at'], name='medical_rep_user_id_3eedf4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrecommendation',
            index=models.Index(fields=['user', 'status'], name='medical_rep_user_id_639bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrecommendation',
            index=models.Index(fields=['report', 'status'], name='medical_rep_report__fc1723_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationrecommendation',
            index=models.Index(fields=['-priority', '-created_at'], name='medical_rep_priorit_74fc87_idx'),
        ),
        migrations.AddIndex(
            model_name='biomarker',
            index=models.Index(fields=['user', 'name', '-test_date'], name='medical_rep_user_id_0cc24d_idx'),
        ),
    ]
