# Generated by Django 5.2.3 on 2025-11-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0002_uploadedmedicalreport_medicationrecommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarker',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_biomarkers', to='medical_reports.uploadedmedicalreport'),
        ),
    ]
