# Generated by Django 5.2.3 on 2025-08-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_agent_conservation_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_conservation_choice',
            field=models.CharField(blank=True, choices=[('S', 'Short'), ('M', 'Medium'), ('D', 'Detailed')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='S', max_length=1, null=True),
        ),
    ]
