# Generated by Django 5.2.3 on 2025-11-20 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('report_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_doses_scheduled', models.IntegerField(default=0)),
                ('doses_taken', models.IntegerField(default=0)),
                ('doses_missed', models.IntegerField(default=0)),
                ('doses_late', models.IntegerField(default=0)),
                ('adherence_percentage', models.FloatField(default=0)),
                ('side_effects_reported', models.JSONField(default=list)),
                ('side_effects_count', models.IntegerField(default=0)),
                ('sleep_quality_avg', models.CharField(blank=True, max_length=20, null=True)),
                ('energy_level_avg', models.CharField(blank=True, max_length=20, null=True)),
                ('mood_observations', models.TextField(blank=True, null=True)),
                ('symptom_observations', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_observations', models.TextField(blank=True, null=True)),
                ('ai_recommendations', models.TextField(blank=True, null=True)),
                ('ai_concerns', models.TextField(blank=True, null=True)),
                ('conversation_count', models.IntegerField(default=0)),
                ('conversations_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='patient_reports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_reports',
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('user', 'report_type', 'report_date')},
            },
        ),
    ]
