# Generated by Django 5.2.3 on 2025-11-20 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_patient_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(choices=[('medication', 'Medication'), ('sleep', 'Sleep'), ('mood', 'Mood'), ('symptom', 'Symptom'), ('side_effect', 'Side Effect'), ('fall', 'Fall'), ('pain', 'Pain'), ('energy', 'Energy'), ('appetite', 'Appetite'), ('vital', 'Vital Sign'), ('general', 'General')], max_length=20)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('medication_id', models.IntegerField(blank=True, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_insight', models.TextField(blank=True, null=True)),
                ('ai_concern_level', models.IntegerField(default=0)),
                ('requires_attention', models.BooleanField(default=False)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='voice', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_observations',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['user', 'observation_type', 'observed_at'], name='patient_obs_user_id_060cde_idx'), models.Index(fields=['user', 'requires_attention'], name='patient_obs_user_id_93669b_idx')],
            },
        ),
    ]
