# Generated by Django 5.2.3 on 2025-11-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_patient_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit_system',
            field=models.CharField(choices=[('US', 'US Standard (mg/dL, lbs, °F)'), ('SI', 'International SI (mmol/L, kg, °C)')], default='US', help_text='Preferred unit system for lab values and measurements', max_length=2),
        ),
    ]
