# Generated by Django 5.2.3 on 2025-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_unit_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
