# Generated by Django 5.2.3 on 2025-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='adherence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='ai_doctor_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='ai_medication_insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='ai_patient_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='ai_side_effect_correlations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='ai_sleep_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='ai_vitals_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='biomarker_trends',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='fall_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='fall_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='medication_analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='overall_health_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='sleep_analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='sleep_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='vitals_analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='vitals_score',
            field=models.IntegerField(default=0),
        ),
    ]
