# Generated by Django 5.2.3 on 2025-12-05 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_enhanced_report_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('family', 'Family Member'), ('caregiver', 'Caregiver'), ('emergency', 'Emergency Contact'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('other', 'Other')], default='family', max_length=20)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('caregiver', 'Caregiver'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('other', 'Other')], default='other', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('facetime_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_contacts',
                'ordering': ['-is_emergency', '-is_primary', 'name'],
            },
        ),
    ]
