# Generated by Django 5.2.3 on 2026-01-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_contact_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
