# Generated by Django 5.2.3 on 2026-01-02 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_report_progress_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('call', 'Phone Call'), ('facetime_video', 'FaceTime Video'), ('facetime_audio', 'FaceTime Audio'), ('message', 'Text Message')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shown', 'Shown to User'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('agent_reason', models.TextField(blank=True, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communication_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='communicati_user_id_4de7fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('given_name', models.CharField(blank=True, max_length=100)),
                ('family_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_numbers', models.JSONField(default=list)),
                ('emails', models.JSONField(default=list)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_contacts',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['user', 'full_name'], name='device_cont_user_id_cd8ec7_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
