# Generated by Django 5.2.3 on 2026-01-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_device_contacts_and_communication_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_agent_medication_updates',
            field=models.BooleanField(default=False, help_text='Allow Kindura AI to mark medications as taken/missed via voice commands'),
        ),
    ]
