# Generated by Django 5.2.3 on 2026-01-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_agent_medication_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extended_vitals_enabled',
            field=models.BooleanField(default=False, help_text='Enable collection of extended HealthKit vitals (walking steadiness, blood glucose, VO2 max, mobility metrics, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='vitals_retention_days',
            field=models.IntegerField(choices=[(30, '30 days'), (60, '60 days')], default=60, help_text='Number of days to retain health vitals data (30 or 60 days max)'),
        ),
    ]
