# Generated by Django 5.2.3 on 2026-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_extended_vitals_and_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extended_vitals_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Individual toggle for each extended vital. Keys: walking_steadiness, blood_pressure, blood_glucose, body_temperature, wrist_temperature, vo2_max, afib_detection, six_min_walk, walking_asymmetry, walking_speed, double_support_time, stair_ascent, stair_descent, peripheral_perfusion'),
        ),
    ]
