# Generated by Django 5.2.3 on 2026-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_extended_vitals_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='activity_analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='clinical_analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='mobility_analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
