# Generated by Django 5.2.3 on 2025-09-14 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_name', models.CharField(db_index=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('patch', 'Patch'), ('inhaler', 'Inhaler'), ('cream', 'Cream'), ('drops', 'Drops'), ('other', 'Other')], default='tablet', max_length=50)),
                ('strength', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('strength_unit', models.CharField(choices=[('mg', 'mg'), ('mcg', 'mcg'), ('g', 'g'), ('ml', 'ml'), ('units', 'units'), ('percentage', '%')], default='mg', max_length=20)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('sublingual', 'Sublingual'), ('injection', 'Injection'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('transdermal', 'Transdermal'), ('nasal', 'Nasal'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic')], default='oral', max_length=50)),
                ('instructions_text', models.TextField(blank=True, help_text='Detailed instructions for taking medication')),
                ('take_with_food', models.BooleanField(blank=True, help_text="True=with food, False=empty stomach, None=doesn't matter", null=True)),
                ('as_needed', models.BooleanField(default=False, help_text='PRN medication')),
                ('schedule', models.JSONField(default=dict, help_text='Schedule containing times and days')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50)),
                ('prescriber', models.CharField(blank=True, max_length=200, null=True)),
                ('prescription_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('prescription', 'From Prescription'), ('report', 'From Medical Report'), ('import', 'Imported')], default='manual', max_length=50)),
                ('source_document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.IntegerField(default=0, help_text='Minutes before scheduled time to remind')),
                ('caregiver_escalation_enabled', models.BooleanField(default=False)),
                ('escalation_delay_minutes', models.IntegerField(default=20, help_text='Minutes after missed dose to notify caregiver')),
                ('snooze_enabled', models.BooleanField(default=True)),
                ('max_snooze_count', models.IntegerField(default=3)),
                ('snooze_duration_minutes', models.IntegerField(default=10)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='medicines.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('clinical_significance', models.TextField(blank=True, null=True)),
                ('management_strategy', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_by_user', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_interactions', to=settings.AUTH_USER_MODEL)),
                ('medication_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_first', to='medicines.medicine')),
                ('medication_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_second', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('taken', 'Taken'), ('late', 'Late'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('snoozed', 'Snoozed')], default='scheduled', max_length=20)),
                ('delay_minutes', models.IntegerField(blank=True, help_text='Minutes late if taken late', null=True)),
                ('side_effect_note', models.TextField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('auto', 'Automatic'), ('voice', 'Voice Command')], default='patient', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdherenceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('on_time_doses', models.IntegerField(default=0)),
                ('late_doses', models.IntegerField(default=0)),
                ('missed_doses', models.IntegerField(default=0)),
                ('total_doses', models.IntegerField(default=0)),
                ('adherence_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='medicines_m_user_id_7ce9a4_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['user', 'is_active'], name='medicines_m_user_id_7fd73f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['drug_name'], name='medicines_m_drug_na_d67453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationinteraction',
            unique_together={('medication_1', 'medication_2')},
        ),
        migrations.AddIndex(
            model_name='medicationevent',
            index=models.Index(fields=['medication', 'scheduled_at'], name='medicines_m_medicat_398f36_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationevent',
            index=models.Index(fields=['status', 'scheduled_at'], name='medicines_m_status_7f56c9_idx'),
        ),
    ]
