# Generated by Django 5.2.3 on 2025-11-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='missed_dose_action',
            field=models.CharField(choices=[('skip_dose', 'Skip and take next dose at regular time'), ('take_asap', 'Take as soon as possible'), ('take_and_shift', 'Take now and shift next doses'), ('contact_doctor', 'Contact doctor for guidance'), ('no_policy', 'No specific policy set')], default='no_policy', help_text='Action to take when a dose is missed', max_length=50),
        ),
    ]
